/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialsIndexRouteImport } from './routes/materials/index'
import { Route as MaterialsSlugRouteImport } from './routes/materials/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCreate_materiRouteImport } from './routes/admin/create_materi'
import { Route as AdminMaterialsNewRouteImport } from './routes/admin/materials/new'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsSlugRoute = MaterialsSlugRouteImport.update({
  id: '/materials/$slug',
  path: '/materials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreate_materiRoute = AdminCreate_materiRouteImport.update({
  id: '/admin/create_materi',
  path: '/admin/create_materi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaterialsNewRoute = AdminMaterialsNewRouteImport.update({
  id: '/admin/materials/new',
  path: '/admin/materials/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRoute
  '/admin/create_materi': typeof AdminCreate_materiRoute
  '/admin/login': typeof AdminLoginRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/materials/': typeof MaterialsIndexRoute
  '/admin/materials/new': typeof AdminMaterialsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRoute
  '/admin/create_materi': typeof AdminCreate_materiRoute
  '/admin/login': typeof AdminLoginRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/materials': typeof MaterialsIndexRoute
  '/admin/materials/new': typeof AdminMaterialsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRoute
  '/admin/create_materi': typeof AdminCreate_materiRoute
  '/admin/login': typeof AdminLoginRoute
  '/materials/$slug': typeof MaterialsSlugRoute
  '/materials/': typeof MaterialsIndexRoute
  '/admin/materials/new': typeof AdminMaterialsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/projects'
    | '/admin/create_materi'
    | '/admin/login'
    | '/materials/$slug'
    | '/materials/'
    | '/admin/materials/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/projects'
    | '/admin/create_materi'
    | '/admin/login'
    | '/materials/$slug'
    | '/materials'
    | '/admin/materials/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/projects'
    | '/admin/create_materi'
    | '/admin/login'
    | '/materials/$slug'
    | '/materials/'
    | '/admin/materials/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectsRoute: typeof ProjectsRoute
  AdminCreate_materiRoute: typeof AdminCreate_materiRoute
  AdminLoginRoute: typeof AdminLoginRoute
  MaterialsSlugRoute: typeof MaterialsSlugRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
  AdminMaterialsNewRoute: typeof AdminMaterialsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/': {
      id: '/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$slug': {
      id: '/materials/$slug'
      path: '/materials/$slug'
      fullPath: '/materials/$slug'
      preLoaderRoute: typeof MaterialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create_materi': {
      id: '/admin/create_materi'
      path: '/admin/create_materi'
      fullPath: '/admin/create_materi'
      preLoaderRoute: typeof AdminCreate_materiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/materials/new': {
      id: '/admin/materials/new'
      path: '/admin/materials/new'
      fullPath: '/admin/materials/new'
      preLoaderRoute: typeof AdminMaterialsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectsRoute: ProjectsRoute,
  AdminCreate_materiRoute: AdminCreate_materiRoute,
  AdminLoginRoute: AdminLoginRoute,
  MaterialsSlugRoute: MaterialsSlugRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
  AdminMaterialsNewRoute: AdminMaterialsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
